### ISSUE TITLE
Parsing error when importing into Fight Club 5

### ISSUE THREAD

**Issue by Username4723** [Cphrampus/DnDAppFiles#409]
Error: `FEAT Aberrant Mind: Revelation in Flesh: expected: END_TAG{null}text (position:START_TAG <text>@9580:11 in java.io.InputStreamReader@27542c4`

Logcat output from import:
```
11-02 10:01:10.619   951  3399 I ActivityTaskManager: START u0 {flg=0x3000000 cmp=com.android.systemui/.chooser.ChooserActivity (has extras)} from uid 1000
11-02 10:01:10.621   693   693 D QCOM PowerHAL: LAUNCH HINT: ON
11-02 10:01:10.640  5920  5920 W APSResolverComparator: Score requested for unknown component.
11-02 10:01:10.643  5942  5942 W ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@fdbd445
11-02 10:01:10.656   951  7996 I ActivityTaskManager: START u0 {act=android.intent.action.GET_CONTENT cat=[android.intent.category.OPENABLE] typ=*/* flg=0x3000000 cmp=com.android.documentsui/.picker.PickActivity} from uid 10241
11-02 10:01:10.657   693   693 D QCOM PowerHAL: LAUNCH HINT: ON
11-02 10:01:10.670  5965  5965 W ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@7edb3c8
11-02 10:01:10.826   951  1004 I ActivityTaskManager: Displayed com.android.documentsui/.picker.PickActivity: +241ms
11-02 10:01:10.851  5965  5965 W DocumentsSwipeRefreshLayout: Retrive colorPrimary colorId from theme fail, assign R.color.primary
11-02 10:01:10.861   693   693 D QCOM PowerHAL: LAUNCH HINT: OFF
11-02 10:01:12.412  5780  6229 W System.err: java.lang.NumberFormatException: For input string: "PROF"
11-02 10:01:12.413  5780  6229 W System.err: 	at java.lang.Integer.parseInt(Integer.java:615)
11-02 10:01:12.413  5780  6229 W System.err: 	at java.lang.Integer.valueOf(Integer.java:801)
11-02 10:01:12.413  5780  6229 W System.err: 	at com.lionsden.fightclub5.logic.Common.convertStringToInt(Common.java:82)
11-02 10:01:12.413  5780  6229 W System.err: 	at com.lionsden.fightclub5.data.DataImporter.convertModifierValue(DataImporter.java:931)
11-02 10:01:12.413  5780  6229 W System.err: 	at com.lionsden.fightclub5.data.DataImporter.load(DataImporter.java:175)
11-02 10:01:12.413  5780  6229 W System.err: 	at com.lionsden.fightclub5.data.DataImporter.loadUri(DataImporter.java:60)
11-02 10:01:12.413  5780  6229 W System.err: 	at com.lionsden.fightclub5.data.DataManager$ImportTask.doInBackground(DataManager.java:629)
11-02 10:01:12.413  5780  6229 W System.err: 	at com.lionsden.fightclub5.data.DataManager$ImportTask.doInBackground(DataManager.java:617)
11-02 10:01:12.413  5780  6229 W System.err: 	at android.os.AsyncTask$3.call(AsyncTask.java:378)
11-02 10:01:12.413  5780  6229 W System.err: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
11-02 10:01:12.413  5780  6229 W System.err: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
11-02 10:01:12.413  5780  6229 W System.err: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
11-02 10:01:12.413  5780  6229 W System.err: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
11-02 10:01:12.413  5780  6229 W System.err: 	at java.lang.Thread.run(Thread.java:919)
11-02 10:01:12.454  5780  6229 W System.err: java.lang.NumberFormatException: For input string: "PROF"
11-02 10:01:12.454  5780  6229 W System.err: 	at java.lang.Integer.parseInt(Integer.java:615)
11-02 10:01:12.454  5780  6229 W System.err: 	at java.lang.Integer.valueOf(Integer.java:801)
11-02 10:01:12.454  5780  6229 W System.err: 	at com.lionsden.fightclub5.logic.Common.convertStringToInt(Common.java:82)
11-02 10:01:12.454  5780  6229 W System.err: 	at com.lionsden.fightclub5.data.DataImporter.convertModifierValue(DataImporter.java:931)
11-02 10:01:12.454  5780  6229 W System.err: 	at com.lionsden.fightclub5.data.DataImporter.load(DataImporter.java:175)
11-02 10:01:12.454  5780  6229 W System.err: 	at com.lionsden.fightclub5.data.DataImporter.loadUri(DataImporter.java:60)
11-02 10:01:12.454  5780  6229 W System.err: 	at com.lionsden.fightclub5.data.DataManager$ImportTask.doInBackground(DataManager.java:629)
11-02 10:01:12.454  5780  6229 W System.err: 	at com.lionsden.fightclub5.data.DataManager$ImportTask.doInBackground(DataManager.java:617)
11-02 10:01:12.454  5780  6229 W System.err: 	at android.os.AsyncTask$3.call(AsyncTask.java:378)
11-02 10:01:12.454  5780  6229 W System.err: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
11-02 10:01:12.454  5780  6229 W System.err: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
11-02 10:01:12.454  5780  6229 W System.err: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
11-02 10:01:12.454  5780  6229 W System.err: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
11-02 10:01:12.454  5780  6229 W System.err: 	at java.lang.Thread.run(Thread.java:919)
11-02 10:01:12.454  5780  6229 W System.err: java.lang.NumberFormatException: For input string: "PROF"
11-02 10:01:12.454  5780  6229 W System.err: 	at java.lang.Integer.parseInt(Integer.java:615)
11-02 10:01:12.454  5780  6229 W System.err: 	at java.lang.Integer.valueOf(Integer.java:801)
11-02 10:01:12.454  5780  6229 W System.err: 	at com.lionsden.fightclub5.logic.Common.convertStringToInt(Common.java:82)
11-02 10:01:12.454  5780  6229 W System.err: 	at com.lionsden.fightclub5.data.DataImporter.convertModifierValue(DataImporter.java:931)
11-02 10:01:12.454  5780  6229 W System.err: 	at com.lionsden.fightclub5.data.DataImporter.load(DataImporter.java:175)
11-02 10:01:12.454  5780  6229 W System.err: 	at com.lionsden.fightclub5.data.DataImporter.loadUri(DataImporter.java:60)
11-02 10:01:12.454  5780  6229 W System.err: 	at com.lionsden.fightclub5.data.DataManager$ImportTask.doInBackground(DataManager.java:629)
11-02 10:01:12.454  5780  6229 W System.err: 	at com.lionsden.fightclub5.data.DataManager$ImportTask.doInBackground(DataManager.java:617)
11-02 10:01:12.454  5780  6229 W System.err: 	at android.os.AsyncTask$3.call(AsyncTask.java:378)
11-02 10:01:12.454  5780  6229 W System.err: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
11-02 10:01:12.454  5780  6229 W System.err: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
11-02 10:01:12.454  5780  6229 W System.err: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
11-02 10:01:12.454  5780  6229 W System.err: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
11-02 10:01:12.454  5780  6229 W System.err: 	at java.lang.Thread.run(Thread.java:919)
11-02 10:01:12.462  5780  6229 W System.err: org.xmlpull.v1.XmlPullParserException: expected: END_TAG {null}text (position:START_TAG <text>@9580:11 in java.io.InputStreamReader@6e2a073) 
11-02 10:01:12.462  5780  6229 W System.err: 	at com.android.org.kxml2.io.KXmlParser.require(KXmlParser.java:2067)
11-02 10:01:12.462  5780  6229 W System.err: 	at com.lionsden.fightclub5.data.DataImporter.readAppendText(DataImporter.java:635)
11-02 10:01:12.462  5780  6229 W System.err: 	at com.lionsden.fightclub5.data.DataImporter.load(DataImporter.java:277)
11-02 10:01:12.462  5780  6229 W System.err: 	at com.lionsden.fightclub5.data.DataImporter.loadUri(DataImporter.java:60)
11-02 10:01:12.462  5780  6229 W System.err: 	at com.lionsden.fightclub5.data.DataManager$ImportTask.doInBackground(DataManager.java:629)
11-02 10:01:12.462  5780  6229 W System.err: 	at com.lionsden.fightclub5.data.DataManager$ImportTask.doInBackground(DataManager.java:617)
11-02 10:01:12.462  5780  6229 W System.err: 	at android.os.AsyncTask$3.call(AsyncTask.java:378)
11-02 10:01:12.462  5780  6229 W System.err: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
11-02 10:01:12.462  5780  6229 W System.err: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
11-02 10:01:12.462  5780  6229 W System.err: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
11-02 10:01:12.462  5780  6229 W System.err: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
11-02 10:01:12.462  5780  6229 W System.err: 	at java.lang.Thread.run(Thread.java:919)
11-02 10:01:14.021  6852  6898 W Notification: Use of stream types is deprecated for operations other than volume control
11-02 10:01:14.021  6852  6898 W Notification: See the documentation of setSound() for what to use instead with android.media.AudioAttributes to qualify your playback use case
11-02 10:01:17.251   689   689 I /vendor/bin/hw/android.hardware.health@2.0-service.marlin: SRAM data: 3470000
11-02 10:01:17.274  6852  6852 I M.PowerCycleState: Percentage changed to 62.0, updated to-100%-mAh to 388.3688024294445
11-02 10:01:17.287  6852  6898 W Notification: Use of stream types is deprecated for operations other than volume control
11-02 10:01:17.287  6852  6898 W Notification: See the documentation of setSound() for what to use instead with android.media.AudioAttributes to qualify your playback use case
11-02 10:01:17.324   693   693 E QCOM PowerHAL: extract_stats: failed to open: /d/wlan_wcnss/power_stats Error = No such file or directory
11-02 10:01:17.350  1478  1999 D PowerUI : can't show warning due to - plugged: true status unknown: false
```
Steps taken to reproduce:
Create `Full Compendium.xml` with `python create_compendiums.py`
Move the file to the device with `adb push`
Import the compendium

**Comment by Cphrampus** [comment]
resolved with #408
